version: '3'
services:
    node-app:
        image: node:latest
        user: 'node'
        working_dir: /src/app
        container_name: node-app
        ports:
            - '5555:5000'
        depends_on:
            - postgres-db
        environment:
            POSTGRES_HOST: postgres-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./:/src/app
        command: 'npm start'
    postgres-db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - database_data:/var/lib/postgresql/data

volumes:
    database_data:
